# -*- coding: utf-8 -*-
"""text generation code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jgnQy72MZlafudlicKV54OSCo1JRMzl9
"""

pip install transformers torch

from transformers import pipeline
#load text generation model(gen AI)
generator=pipeline (
    "text-generation",
    model = "gpt2"
)
#Input prompt
prompt = "Artificial Intelligence in finance will"
#generate text
result = generator(prompt,max_length=50,num_return_sequences = 1)
print("AI Generated Text :")
print (result[0]['generated text'])